### ISSUE TITLE
Axios expect(mockFn).toBeCalled()报错

### ISSUE THREAD

**Issue by kkkman22** [holylovelqq/vue-unit-test-with-jest#10]
![image](https://user-images.githubusercontent.com/23480907/66402444-6e77c080-ea17-11e9-871d-6c55b30706da.png)

**Comment by kkkman22** [comment]
哈哈,我自己解决了! 点击方法多加了个native
![image](https://user-images.githubusercontent.com/23480907/66402967-5bb1bb80-ea18-11e9-86fe-af068215bab9.png)

**Comment by holylovelqq** [comment]
已自行解决
