### ISSUE TITLE
引入Element-UI 的 样式文件报错

### ISSUE THREAD

**Issue by kkkman22** [holylovelqq/vue-unit-test-with-jest#11]
![image](https://user-images.githubusercontent.com/23480907/67146224-9d195500-f2bb-11e9-93b7-9ce434b65ae6.png)

**Comment by holylovelqq** [comment]
@kkkman22 
还没遇到过需要在测试文件里面引入样式文件的？我比较好奇到底是写了什么样的代码。。。
