### ISSUE TITLE
请教 axios post 测试问题 

### ISSUE THREAD

**Issue by dinglittle** [holylovelqq/vue-unit-test-with-jest#2]
如题 , axios 需要 mock , 但是 不知道怎么写 /gg

**Comment by holylovelqq** [comment]
不是很明白您所说的不知道怎么写指什么。

请参看axios测试的例子，里面是用的get。将里面的get换成post/patch/delete等就是相应的测试，如下：

正常获取返回值：axios.get.mockResolvedValue(mockData)-->axios.post.mockResolvedValue(mockData)

请求被rejected：axios.get.mockRejectedValue('error')-->axios.post.mockRejectedValue('error')

为了配合测试还需要在 .vue文件中对应位置添加return即可，缺少测试不通过
