### ISSUE TITLE
运行出现: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)

### ISSUE THREAD

**Issue by AngrygrayWolf** [holylovelqq/vue-unit-test-with-jest#3]
类似之前在vue测试项目出现的[issue](https://github.com/vuejs/vueify/issues/228)。按照他们的解决方法修改`babel.config.js`也不可以。 npm清除缓存重装也无法解决问题。
## 说明
1. 运行测试后，出现如图错误
![image](https://user-images.githubusercontent.com/44916211/58328754-7fa7a280-7e65-11e9-8380-b61354d63e97.png)
提示出现大量的`SyntaxError: 'import' and 'export' may only appear at the top level (2:0)`
2. 环境
`openSUSE 15.0`
`node 10.15.3`
`npm 6.4.1`
3. 感谢大佬。

**Comment by holylovelqq** [comment]
鉴于提出的错误信息，本人重新在windows和mac环境下运行测试均完美通过。并未出现相应问题。
基于每个人的运行环境的本地设置不同，很有可能出现不同的问题，对于此本人也是无能为力。建议自己去解决。尤其linux版本较多。
另外本仓库目的是技术分享交流，即使不能在本地正常运行，也并不影响实质内容。
还是在此提一下本地运行基础环境：
* node：8.12.0(或更高)
* npm：随node一起安装
* vue-cli：v3.3.0（或更高）
* 其他建议最新稳定版
以上，同时关闭本issue，如有疑问欢迎继续提issue
