### ISSUE TITLE
Vue jest测试Data中是JSON数组，通过v-for遍历，怎么去比对这个DOM的期待值

### ISSUE THREAD

**Issue by Qirrei** [holylovelqq/vue-unit-test-with-jest#7]

**Comment by holylovelqq** [comment]
比对DOM的期待值肯定是通过snapshot测试，与data的数据类型和是否通过v-for遍历关系不大

所以我觉得是不是还有什么其他条件你没讲明白，如果只是标题这样的话，最最基本的snapshot测试就覆盖了

**Comment by Qirrei** [comment]
大神，我想问一下就是jest可以进行跨组件进行测试么

**Comment by holylovelqq** [comment]
已提新issue，关闭
