### ISSUE TITLE
我想问一下就是jest可以进行跨组件进行测试么，比如子父组件传值可以将两个组件都能测到

### ISSUE THREAD

**Issue by Qirrei** [holylovelqq/vue-unit-test-with-jest#8]

**Comment by holylovelqq** [comment]
@Qirrei 先回答提问：父组件内可以测试子组件的DOM结构（需要使用mount或者shallowMount+stubs），子组件内无法测试父组件内容。

***但是*** 单元测试不推荐跨组件测试（不排除特殊情况），跨组件就不属于单元测试的范畴了

**Comment by Qirrei** [comment]
@holylovelqq  如果不是子父组件 比如那种兄弟组件可以将这个组件通过mount或者shallowMount挂上去，就可以在这个测试文件中测试另一个组件的DOM结构么

**Comment by holylovelqq** [comment]
@Qirrei 兄弟组件间没有相互引用关系，不能跨组件测试。硬挂没试过，觉得也没意义

**Comment by Qirrei** [comment]
@holylovelqq 大佬，能加下你的微信或者qq么，想详细的跟你了解下

**Comment by holylovelqq** [comment]
@Qirrei 微信号 hhoollyy

**Comment by holylovelqq** [comment]
已解决
