### ISSUE TITLE
更新预定

### ISSUE THREAD

**Issue by holylovelqq** [holylovelqq/vue-unit-test-with-jest#9]
鉴于现存的教程及代码主要面对初学者，貌似不能达到实际中灵活运用的目的，故预定接下来的更新如下
1. 整合仓库布局
   - 大致分为【初学入门】和【高级进阶】两个文件夹
   - 现存的代码保留，作为【初学入门】教程实例
   - 寻找网络上现有未写单测的开源项目（或者其他可使用项目）添加单测，作为【高级进阶】的教程实例、~~如果采取收费模式（见下说明）的话，就只能选择自己以前的练手项目拿来做模版了~~。比较麻烦的将会是选择合适的项目。
2. 现存的代码对于完全0基础的单测入门教程还是比较合适的，简单易懂，涵盖面较广，有助于打基础，如果用心学习，再加上能在实际项目中实践的话（当然最好是有大神带），个人感觉可以完全不用看高级进阶教程。
3. 【高级进阶】----主要更新内容
   - 教程目的：学完以后能独立处理可能出现的单测情况的90%，剩下10%考验的是能否灵活运用，以及对各种复杂情况的应变能力。但是鉴于每个人的吸收能力不同，也不能完全保证。
   - 暂定内容
      - [x] 详解实际项目中的单元测试思路（找准出发点，明确目的，规范代码）
      - [x] 详解实际项目中jest的配置/覆盖率解读（整合网上现有资源，结合经验）
      - [x] 详解snapshot测试原理（理解官网介绍，简单易懂的总结，结合实例）
      - [x] 详解axios单测写法（有别于【初级入门】）
      - [x] 异步测试详解（使用插件flush-promises与不用的写法）
      - [x] vuex测试详解
      - [x] store测试详解
      - [x] vue-router测试详解（一般不需测试）
      - [x] 官方api详解
         - [x] shallowMount与mount https://github.com/holylovelqq/vue-unit-test-with-jest/issues/4
          - [x] stubs/mocks/data/methods等
4. 预定完成日：~~19年内~~ 推迟，日期未定
5. 鉴于高级进阶教程内容可能会比较多，比较杂，~~暂定采取收费模式，目的是能强化其重要性。最终要根据教程内容与完成度决定是否采取收费模式，即便收费也不会太高~~
6. 现存代码基本不做大的调整，教程说明文字有可能会做修改。【高级进阶】尽量实现规范化，增强commit的可读性
7. 目测vue3.0有很大可能也在元旦（或春节）前后推出。从现阶段已经公开的信息来看似乎对测试没有影响，但是也不绝对。如果3.0推出后证明对测试有影响的话，这边也应该及时更新

---随时修改完善---

**Comment by kkkman22** [comment]
大佬，等着你的更新啊

**Comment by holylovelqq** [comment]
已更新完成
